### ISSUE TITLE
datayear and coveragetype are missing in fillgaps

### ISSUE THREAD

**Issue by randrescastaneda** [PIP-Technical-Team/pip#21]
When using the fillgaps option with pip wb, clear, data on datayear and coveragetype are missing. So I am unable to replicate the results from the analysis of the 2017 PPPs. I could solve that manually, but it would be nice to have these data in PIP so that it is more convenient for replication purposes

@tsamuel321 @tonyfujs @Aeilert @Tefera19

**Comment by Aeilert** [comment]
@randrescastaneda 

I think datayear and coveragetype are the same as survey_year and survey_coverage in PIP (correct me if I'm wrong). The reason these are set to NA in the fill_gaps option is that for interpolated poverty stats these columns (and a handful of other metadata cols) are based on two surveys / two rows in the data. They thus don't have a unique value to report.

**Comment by Aeilert** [comment]
This is related to https://github.com/PIP-Technical-Team/pipapi/issues/191. Let's follow up there. 

Closing.
