### ISSUE TITLE
Variables to drop

### ISSUE THREAD

**Issue by randrescastaneda** [PIP-Technical-Team/pip#23]
Hey guys, 

Daniel suggests to drop from the main output the following variables. 

- cpi
- ppp
- pop
- gdp
- pce_data_level 

Right now it is part of the main output and we are not dropping any variable. We could, by default, provide a shorter ser of variables and add an option to load all variables. 

What do you think?

@Aeilert @tonyfujs @danielmahler @Tefera19 @ChristophLakner

**Comment by ChristophLakner** [comment]
Hi Andres,
I think that's a good idea, but perhaps I would keep pop in the main output. If I remember correctly, this is how povcalnet.ado has it and perhaps this would minimize changes needed as users transition.

Thanks,
Christoph

From: R.Andrés Castañeda ***@***.***>
Sent: Tuesday, February 1, 2022 3:08 PM
To: PIP-Technical-Team/pip ***@***.***>
Cc: Christoph Lakner ***@***.***>; Mention ***@***.***>
Subject: [PIP-Technical-Team/pip] Variables to drop (Issue #23)

[External]

Hey guys,

Daniel suggests to drop from the main output the following variables.

  *   cpi
  *   ppp
  *   pop
  *   gdp
  *   pce_data_level

Right now it is part of the main output and we are not dropping any variable. We could, by default, provide a shorter ser of variables and add an option to load all variables.

What do you think?

@Aeilert<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAeilert&data=04%7C01%7Cclakner%40worldbank.org%7Cd94ce4bc77f94f6104cf08d9e5be9aab%7C31a2fec0266b4c67b56e2796d8f59c36%7C0%7C0%7C637793429072714836%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=pkVzz8RsEGwEsYmKtTDDttg8U5rC6xejfLPnjfWnQMo%3D&reserved=0> @tonyfujs<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftonyfujs&data=04%7C01%7Cclakner%40worldbank.org%7Cd94ce4bc77f94f6104cf08d9e5be9aab%7C31a2fec0266b4c67b56e2796d8f59c36%7C0%7C0%7C637793429072714836%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Y8OGtI0AKsOUdH7cQBJAUQwK%2FLhLCLbtArCVb8MLE60%3D&reserved=0> @danielmahler<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdanielmahler&data=04%7C01%7Cclakner%40worldbank.org%7Cd94ce4bc77f94f6104cf08d9e5be9aab%7C31a2fec0266b4c67b56e2796d8f59c36%7C0%7C0%7C637793429072714836%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=2o3LyueL8r3xkppSNRqs5KUDnsgLmu2HaVVptkGgejc%3D&reserved=0> @Tefera19<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTefera19&data=04%7C01%7Cclakner%40worldbank.org%7Cd94ce4bc77f94f6104cf08d9e5be9aab%7C31a2fec0266b4c67b56e2796d8f59c36%7C0%7C0%7C637793429072714836%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DaCZXCLQaKgx1hzujA%2BYfsywcNXhQR9XJXI7M3U060Q%3D&reserved=0> @ChristophLakner<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FChristophLakner&data=04%7C01%7Cclakner%40worldbank.org%7Cd94ce4bc77f94f6104cf08d9e5be9aab%7C31a2fec0266b4c67b56e2796d8f59c36%7C0%7C0%7C637793429072714836%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Um3UPAZ4Em9dq2QwEMwJWNfdf2Mx6SBHH3%2BHJPDhNT0%3D&reserved=0>

-

**Comment by danielmahler** [comment]
Hey Andres, I may have miswritten, but I meant to refer to the following variables:

* cpi_data_level
* ppp_data_level
* pop_data_level
* gdp_data_level
* pce_data_level

I would keep the pop, cpi, gdp, pce (hfce), and ppp variables.

Best,
Daniel

**Comment by Aeilert** [comment]
Thanks all, 

Removing the data_level columns, and a a few others, is something we already plan to do. @randrescastaneda: Fully agree that the /pip response should be as lightweight as possible. There is a issue for this in pipapi. We will follow up there. 

Closing this ticket. 

https://github.com/PIP-Technical-Team/pipapi/issues/183
